test:
	pdflatex testlayout && open testlayout.pdf

open:
	open testlayout.pdf

clean:
	rm testlayout.aux testlayout.out testlayout.log

new: clean
	rm testlayout.pdf

pdf:
	pdflatex testlayout

edit:
	vi testlayout.tex
